# Generated by Django 5.0.4 on 2024-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='media/images/books/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(upload_to='media/chapters/books/'),
        ),
    ]
