# Generated by Django 5.0.4 on 2024-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_image_alter_chapter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(upload_to='media/images/chapter/'),
        ),
    ]
