# Generated by Django 5.0.4 on 2024-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chapter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/books/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(upload_to='images/chapter/'),
        ),
    ]
